apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: panchangam

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: panchangam
  app.kubernetes.io/managed-by: kustomize
